name: Build Registry

on:
  push:
    paths:
      - "registry/**"
  pull_request:
    paths:
      - "registry/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run shadcn build
        run: npx shadcn build
       
      - name: Check build
        run: npx shadcn build --check