# .github/workflows/registry.yml
name: Build Registry

on:
  push:
    branches: [main]
    paths:
      - "src/registry/**"
      - "jsrepo.config.mts"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout le repo
      - uses: actions/checkout@v4

      # 2️⃣ Installer Node (npm inclus)
      - uses: actions/setup-node@v3
        with:
          node-version: 24

      # 3️⃣ Installer les dépendances
      - run: npm install

      # 4️⃣ Build le registry
      - run: npm run registry:build

      # 5️⃣ Commit automatique des fichiers générés
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: rebuild registry"
          file_pattern: "public/r/**"
